[supervisord]
nodaemon=true
pidfile=/tmp/supervisord.pid
logfile=/dev/null
user=root

[unix_http_server]
file=/tmp/supervisor.sock
chmod=0700

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[program:django]
command=/bin/sh -c ". %(ENV_VENV_PATH)s/bin/activate && exec python manage.py runserver 0.0.0.0:8000"
directory=/application
numprocs=1
autostart=true
autorestart=true
startsecs=0
stopwaitsecs=10
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
user=django
environment=HOME="%(ENV_APPLICATION_HOME)s"

[program:logrotate]
command=/bin/sh -c "while true; do /usr/sbin/logrotate -s /tmp/logrotate.status /etc/logrotate.conf; sleep 3600; done"
directory=/application
numprocs=1
autostart=true
autorestart=true
startsecs=0
stopwaitsecs=10
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:crond]
command=/usr/sbin/crond -f -l 8 -c /local-config/cron
directory=/application
numprocs=1
autostart=true
autorestart=true
startsecs=0
stopwaitsecs=10
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
