# Generated by Django 6.0.7 on 2026-10-07 11:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fn', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^\\d{16}$', 'ФН должен содержать 16 цифр')], verbose_name='ФН')),
                ('fd', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$', 'ФД должен содержать от 1 до 10 цифр')], verbose_name='ФД')),
                ('fp', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$', 'ФП должен содержать от 1 до 10 цифр')], verbose_name='ФП')),
                ('purchased_at', models.DateTimeField(verbose_name='Дата покупки')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1000.00'))], verbose_name='Сумма')),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('accepted', 'Принят'), ('rejected', 'Отклонён')], default='pending', max_length=10, verbose_name='Статус')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Причина отказа')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата регистрации')),
                ('is_demo', models.BooleanField(default=False, editable=False, verbose_name='Тестовый чек')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Чек',
                'verbose_name_plural': 'Чеки',
                'ordering': ['-created_at', '-pk'],
                'constraints': [models.UniqueConstraint(fields=('fn', 'fd', 'fp'), name='receipt_unique_fiscal_details'), models.CheckConstraint(condition=models.Q(('amount__gte', 1000)), name='receipt_minimum_amount'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'rejected'), _negated=True), models.Q(('rejection_reason', ''), _negated=True), _connector='OR'), name='receipt_rejected_requires_reason'), models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'accepted', 'rejected'])), name='receipt_valid_status')],
            },
        ),
    ]
